Wiki
baxter-oop/AndOre pull request #251
Opened 2016-12-02 19:15 UTC by mcdfinn

Added Heath Potion wiki page, as well as fixing Turret's page.

2016-12-05 18:33 UTC, TheCoub approved these changes

2016-12-05 19:46 UTC, JCharante requested changes
Let me know when you address these comments.

2016-12-05 19:46 UTC, JCharante commented on wiki/heath_potion.md
> +Turrets
Are you high? This file is about Health Potions so the title should be `Health Potions`

2016-12-05 19:46 UTC, JCharante commented on wiki/heath_potion.md
> +* Cost: `50 Ore`
Use this following formatting instead. The below values are placeholders.

* Cost:
    * Construction Cost: 1
    * Buy from Pharmacy with `M` standing: 5
    * Buy from Pharmacy with `A` standing: 10
    * Buy from Pharmacy with `N` standing: 15
    * Buy from Pharmacy with `E` standing: 20

2016-12-05 19:46 UTC, JCharante commented on wiki/heath_potion.md
> +Health Potions give the user an instant boost of 15 health directly to their health bar.
To their health bar? That kinda sounds weird. Say this instead

`Health Potions give their user an instant health boost of 15.`

2016-12-05 19:46 UTC, JCharante commented on wiki/heath_potion.md
> +#### Origin
Add a new line before `### Origin`

2016-12-05 19:46 UTC, JCharante commented on wiki/heath_potion.md
> +Health Potions are acquired from the Pharmacy,
Why a new line for the comma?

2016-12-05 19:46 UTC, JCharante commented on wiki/heath_potion.md
> +a corporation owned building. They can be bought by anyone, with varying margins of profit. Members of a corporation (M),(@) gain you no profit. Allies (A) net you 1 ore, Neutrals (N) 5 ore, and Enem
For new sentences, just use a new line as it'll render the same but look neater when editing. Example:

`Line 1 - The bobcat is very silly.`
`Line 2 - The children loved to play with the bobcat, until it got fed up with their unclean smiles and mauled a child.`

renders into

`The bobcat is very silly. The children loved to play with the bobcat, until it got fed up with their unclean smiles and mauled a child.`

2016-12-07 02:07 UTC, JCharante approved these changes

2016-12-07 02:07 UTC, merged